config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :members
  
  resources :articles do
    resources :comments
  end

  get '/home/index', to: 'home#index'

  get '/home/get_companies', to: 'home#show'

  get 'welcome/index'

  root 'welcome#index'
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  load_and_authorize_resource class: User
  add_breadcrumb 'index', :welcome_index_url
  add_breadcrumb 'members', :members_url

  # GET /members
  def index
    @members = User.all.paginate(page: params[:page], per_page: PER_PAGE)
    respond_to do |format|
      format.html
    end
  end

  # GET /members/:id
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /members/new
  def new
    add_breadcrumb 'new', :new_member_url
    respond_to do |format|
      format.html
    end
  end

  # GET /members/:id/edit
  def edit
    add_breadcrumb 'edit', :edit_member_url
    respond_to do |format|
      format.html
    end
  end

  # POST /members
  def create
    @member.role_id = User::ROLES[:User]
    @member.company_id = User.current_user.company_id
    is_successful = @member.save
    respond_to do |format|
      format.html do
        if is_successful
          flash[:notice] = t 'member_created'
          redirect_to members_url
        else
          flash[:alert] = t 'member_not_created'
          render 'new'
        end
      end
    end
  end

  # PATCH /members/:id
  def update
    is_successful = @member.update(member_params)
    respond_to do |format|
      format.html do
        if is_successful
          flash[:notice] = t 'member_updated'
          redirect_to members_url
        else
          flash[:alert] = t 'member_not_updated'
          render 'edit'
        end
      end
    end
  end

  # DELETE /members/:id
  def destroy
    @member.destroy
    is_destroyed = @member.destroyed?
    respond_to do |format|
      format.html do
        if is_destroyed
          flash[:notice] = t 'member_deleted'
          redirect_to members_path
        else
          flash[:alert] = t 'member_not_deleted'
          redirect_to members_path
        end
      end
    end
  end

  private

  def member_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/views/members/_form.html.erb
<% if member.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(member.errors.count, "error") %> prohibited
      this member from being saved:
    </h2>
    <ul>
      <% member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div style="margin-top: 150px;" class="d-flex justify-content-md-center align-items-center ">
  <div style="border:1px solid black; padding:100px; border-radius: 10px;">
    <%= form_with model: member, url: member.persisted? ? member_path(member) : members_url, local: true do |form| %>
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
      <p>
        <%= form.label :email %><br>
        <%= form.email_field :email %>
      </p>
      <% unless member.persisted? %>
        <div class="field">
          <%= form.label :password %>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= form.password_field :password, autocomplete: "new-password" %>
        </div>
        <br>
        <div class="field">
          <%= form.label :password_confirmation %><br />
          <%= form.password_field :password_confirmation,  autocomplete: "new-password" %>
        </div>
      <% end %>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>
</div>

app/views/members/edit.html.erb
<h1><%= t 'edit_user' %></h1>
<%= link_to 'Back', welcome_index_url %>
<%= render partial: 'form', locals: {member: @member} %>

app/views/members/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
<h1><%= t 'all_users' %></h1>
<table class="table table-striped text-center">
  <thead>
    <tr>
      <th><%= t 'table_title' %></th>
      <th><%= t 'table_action' %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_member_path(user) %></td>
        <td><%= link_to 'Destroy', member_path(user),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @members %>

app/views/members/new.html.erb
<h1 class="text-center"><%= t 'new_user' %></h1>
<%= link_to 'Back', welcome_index_url %>
<%= render partial: 'form', locals: {member: @member} %>